name: Build font and mocks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build fonts
      run: |
        grep -h only test/fontbakery/*json | sort -u | perl -nle 'print  $1 if /(Noto[^-]+)/' | while read -r a ; do fontmake -g src/$a.glyphs -o ttf ; done
    - name: Test
      run: |
        fontbakery check-profile --html report.html --config fontbakery.yml fontbakery.profiles.shaping master_ttf/*
      continue-on-error: true
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NotoShapingTests
        path: |
          master_ttf
          report.html
